version: "3.8"
services:
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zip
    networks:
      - api-mysql-net

  application:
    container_name: zipUserApi
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/zip
    depends_on:
      - mysqldb
    networks:
      - api-mysql-net
    restart: on-failure

networks:
  api-mysql-net:
