version: "3.8"
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_USER: agent
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zip
